openapi: 3.0.1
info:
  version: 1.0.0
  title: Serviços Auxiliares
  description: Consulte endereços, liste cidades e pesquise por instituições financeiras. 
servers:
  - url: 'https://api.sandbox.bankly.com.br'
paths:
  /addresses/{zipCode}:
    get:
      tags:
        - Endereços
      parameters:
        - name: zipCode
          in: path
          description: O CEP correspondente ao endereço
          required: true
          schema:
            type: string
            description: O CEP correspondente ao endereço
            nullable: true
            example: '05402100'
      responses:
        '200':
          description: Recurso encontrado

components:
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer.
      scheme: bearer
      bearerFormat: JWT
      
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
