openapi: 3.0.1
info:
  title: Serviços Auxiliares
  description: Consulte endereços, liste cidades e pesquise por instituições financeiras.
  version: '1.0'
servers:
  - url: https://api.sandbox.bankly.com.br
paths:
  /addresses/{zipCode}:
    get:
      tags:
        - Endereços
      summary: Consulta de endereço por CEP
      description: |
        <div class="bkly-ref-description">
          <p>Realize consultas de endereços através do código postal.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: zipcode.read</span>
        </div>
      operationId: GetAddress
      parameters:
        - name: zipCode
          in: path
          description: O CEP correspondente ao endereço
          required: true
          schema:
            type: string
            description: O CEP correspondente ao endereço
            nullable: true
            example: '05402100'
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recurso encontrado
        '400':
          description: Há algum problema com a sua requisição.
        '404':
          description: Recurso não encontrado.
        '500':
          description: Ocorreu algum erro inexperado no nosso servidor.
      security:
        - Bearer: []
  
components:
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer.
      scheme: bearer
      bearerFormat: JWT
      
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
