openapi: 3.0.1
info:
  title: Gestão de boletos
  description: Depósitos e cobranças via boleto em poucos minutos.
  version: '1.0'
servers:
  - url: https://api.sandbox.bankly.com.br
paths:
  /bankslip:
    post:
      tags:
        - Emissão de boleto
      summary: Solicite a emissão de um boleto de depósito
      description: Emita boletos
      operationId: Create
      parameters:
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateBankslipRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBankslipRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateBankslipRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateBankslipRequest'
      responses:
        '202':
          description: Requisição foi aceita e está sendo processada
          headers:
            x-bankly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
            Location:
              description: Localização do recurso recém-criado ou em análise.
              schema:
                type: string
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CreateBankslipResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBankslipResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/CreateBankslipResponse'
      security:
        - Bearer: []
  /bankslip/branch/{branch}/number/{number}/{authenticationCode}:
    get:
      tags:
        - Emissão de boleto
      summary: Obtenha dados do boleto
      description: Utilize para verificar o status do boleto ou outras informações
      operationId: GetByAuthenticationCode
      parameters:
        - name: branch
          in: path
          required: true
          schema:
            type: string
        - name: number
          in: path
          required: true
          schema:
            type: string
        - name: authenticationCode
          in: path
          required: true
          schema:
            type: string
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bankly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetBankslipByAuthenticationCodeResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/GetBankslipByAuthenticationCodeResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/GetBankslipByAuthenticationCodeResponse'
      security:
        - Bearer: []
  /bankslip/{authenticationCode}/pdf:
    get:
      tags:
        - Emissão de boleto
      summary: Imprimir boleto
      description: Realiza a impressão em PDF do boleto emitido
      operationId: GetPDF
      parameters:
        - name: authenticationCode
          in: path
          description: Identificador de emissão do boleto
          required: true
          schema:
            minLength: 1
            type: string
            description: Identificador de emissão do boleto
            format: uuid
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bankly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
  /bankslip/searchstatus/{date}:
    get:
      tags:
        - Emissão de boleto
      summary: Pesquisa de boletos por data
      description: Utilize para listar os status dos boletos por data
      operationId: SearchStatus
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date-time
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bankly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SearchResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
      security:
        - Bearer: []
  /bankslip/cancel:
    delete:
      tags:
        - Cancelamento de boleto
      summary: Solicitar o cancelamento de um boleto.
      description: Cancela boletos
      operationId: SettlementCancellation
      parameters:
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipCancellationRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipCancellationRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipCancellationRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipCancellationRequest'
      responses:
        '200':
          description: Requisição foi aceita e está sendo processada
          headers:
            x-bankly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
      security:
        - Bearer: []
  /bankslip/settlementpayment:
    post:
      tags:
        - Baixa Efetiva
      summary: Simular pagamento de um boleto.
      description: Paga boletos
      operationId: SettlementPayment
      parameters:
        - name: api-version
          in: header
          description: Versão da API. Atualmente estamos na 1.0.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipPaymentRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipPaymentRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipPaymentRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SettlementBankslipPaymentRequest'
      responses:
        '200':
          description: Requisição foi aceita e está sendo processada
          headers:
            x-bankly-correlation-id:
              description: Id correlação da operação requisitada.
              schema:
                type: string
      security:
        - Bearer: []
components:
  schemas:
    Account:
      type: object
      properties:
        number:
          type: string
          description: Número da conta.
          nullable: true
        branch:
          type: string
          description: Agência da conta.
          nullable: true
      additionalProperties: false
    BankslipType:
      enum:
        - Deposit
        - Levy
      type: string
    Address:
      type: object
      properties:
        addressLine:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        state:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true
      additionalProperties: false
    Person:
      type: object
      properties:
        document:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        tradeName:
          type: string
          nullable: true
        address:
          $ref: '#/components/schemas/Address'
      additionalProperties: false
    CreateBankslipRequest:
      required:
        - amount
      type: object
      properties:
        alias:
          type: string
          description: Identificador externo do boleto.
          nullable: true
        account:
          $ref: '#/components/schemas/Account'
        documentNumber:
          type: string
          description: CPF ou CNPJ do emissor.
          nullable: true
        amount:
          maximum: 92233720368547760
          exclusiveMaximum: true
          minimum: 0
          exclusiveMinimum: true
          minLength: 1
          type: number
          description: Valor do boleto.
          format: double
        dueDate:
          type: string
          description: Data de vencimento
          format: date-time
        type:
          $ref: '#/components/schemas/BankslipType'
        payer:
          $ref: '#/components/schemas/Person'
      additionalProperties: false
    CreateBankslipResponse:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'
        authenticationCode:
          type: string
          format: uuid
      additionalProperties: false
    GetBankslipByAuthenticationCodeRequest:
      required:
        - authenticationCode
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'
        authenticationCode:
          minLength: 1
          type: string
          description: Identificador de emissão do boleto
          format: uuid
      additionalProperties: false
    BankslipStatus:
      enum:
        - Accepted
        - Registered
        - Settled
        - Error
        - Cancelled
        - Expired
      type: string
    PriceValue:
      type: object
      properties:
        currency:
          type: string
          nullable: true
          readOnly: true
        value:
          type: number
          format: double
      additionalProperties: false
    PaymentChannelType:
      enum:
        - Agency
        - SelfServiceTerminal
        - InternetBanking
        - CorrespondentBanking
        - CallCenter
        - EletronicFile
        - DDA
      type: string
    Payments:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: number
          format: double
        paymentChannel:
          $ref: '#/components/schemas/PaymentChannelType'
        paidOutDate:
          type: string
          format: date-time
      additionalProperties: false
    GetBankslipByAuthenticationCodeResponse:
      type: object
      properties:
        authenticationCode:
          type: string
          format: uuid
        updatedAt:
          type: string
          format: date-time
        ourNumber:
          type: string
          nullable: true
        digitable:
          type: string
          nullable: true
        status:
          $ref: '#/components/schemas/BankslipStatus'
        account:
          $ref: '#/components/schemas/Account'
        document:
          type: string
          nullable: true
        amount:
          $ref: '#/components/schemas/PriceValue'
        dueDate:
          type: string
          format: date-time
        emissionDate:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/BankslipType'
        payer:
          $ref: '#/components/schemas/Person'
        recipientFinal:
          $ref: '#/components/schemas/Person'
        recipientOrigin:
          $ref: '#/components/schemas/Person'
        payments:
          type: array
          items:
            $ref: '#/components/schemas/Payments'
          nullable: true
      additionalProperties: false
    GetBankslipByBarcodeResponse:
      type: object
      properties:
        authenticationCode:
          type: string
          format: uuid
        updatedAt:
          type: string
          format: date-time
        ourNumber:
          type: string
          nullable: true
        digitable:
          type: string
          nullable: true
        status:
          $ref: '#/components/schemas/BankslipStatus'
        account:
          $ref: '#/components/schemas/Account'
        document:
          type: string
          nullable: true
        amount:
          $ref: '#/components/schemas/PriceValue'
        dueDate:
          type: string
          format: date-time
        emissionDate:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/BankslipType'
        payer:
          $ref: '#/components/schemas/Person'
        recipientFinal:
          $ref: '#/components/schemas/Person'
        recipientOrigin:
          $ref: '#/components/schemas/Person'
        payments:
          type: array
          items:
            $ref: '#/components/schemas/Payments'
          nullable: true
      additionalProperties: false
    GeneratePDFRequest:
      required:
        - authenticationCode
      type: object
      properties:
        authenticationCode:
          minLength: 1
          type: string
          description: Identificador de emissão do boleto
          format: uuid
      additionalProperties: false
    SearchRequest:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'
        status:
          $ref: '#/components/schemas/BankslipStatus'
        pageSize:
          type: integer
          format: int32
        pageToken:
          type: string
          nullable: true
      additionalProperties: false
    SearchItemResponse:
      type: object
      properties:
        alias:
          type: string
          nullable: true
        recipientOrigin:
          $ref: '#/components/schemas/Person'
        recipientFinal:
          $ref: '#/components/schemas/Person'
        payer:
          $ref: '#/components/schemas/Person'
        barcode:
          type: string
          nullable: true
        digitable:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date-time
        amount:
          $ref: '#/components/schemas/PriceValue'
        authenticationCode:
          type: string
          nullable: true
        emissionDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/BankslipStatus'
        payments:
          type: array
          items:
            $ref: '#/components/schemas/Payments'
          nullable: true
      additionalProperties: false
    SearchResponse:
      type: object
      properties:
        nextPageToken:
          type: string
          nullable: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/SearchItemResponse'
          nullable: true
      additionalProperties: false
    SettlementBankslipCancellationRequest:
      required:
        - authenticationCode
      type: object
      properties:
        authenticationCode:
          minLength: 1
          type: string
          description: Identificador de emissão do boleto
          format: uuid
        account:
          $ref: '#/components/schemas/Account'
      additionalProperties: false
    SettlementBankslipPaymentRequest:
      required:
        - authenticationCode
      type: object
      properties:
        authenticationCode:
          minLength: 1
          type: string
          description: Identificador de emissão do boleto
          format: uuid
        account:
          $ref: '#/components/schemas/Account'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
      bearerFormat: JWT
      
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
