openapi: 3.0.1
info:
  title: Transações bandeiradas com cartões
  description: API para autenticação de transações bandeiradas através do protocolo Flow3DS
  version: '1.0'
servers:
  - url: https://api.sandbox.bankly.com.br
paths:
  /card-network-transactions/simulator/challenge:
    post:
      tags:
        - Autorizador 3DS
      summary: Simulador de criação do desafio
      description:  |
        <div class="bkly-ref-description">
          <p>Teste o fluxo de autenticação 3DS, simulando a criação do desafio que será enviado a seu cliente. </p> 
          <span class="bkly-ref-small-stable-tag">stable</span>
          <span class="bkly-ref-scope-tag">scope: card.network.transactions.3ds.write</span>
        </div>
        [block:callout]
        {
          "type": "info",
          "title": "Importante",
          "body": "Este endpoint funciona apenas em ambiente de sandbox."
        }
        [/block]
      parameters:
        - $ref: "#/components/parameters/apiVersion"
        - $ref: "#/components/parameters/authorization"
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateChallengeSimulatorCommand'
      responses:
        '201':
          description: Desafio criado com sucesso.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChallengeSimulatorResponse"
      security:
        - Bearer: [ ]
  /card-network-transactions/authentication/challenge/{challengeId}/confirm:
    patch:
      tags:
        - Autorizador 3DS
      summary: Confirmação do desafio
      description:  |
        <div class="bkly-ref-description">
          <p>Após o seu cliente responder o desafio, utilize este endpoint para confirmar ou não a sua identidade.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> 
          <span class="bkly-ref-scope-tag">scope: card.network.transactions.3ds.write</span>
        </div>  
      parameters:
        - name: challengeId
          in: path
          required: true
          description: Id retornado após a criação do desafio.
          schema:
            type: string
            nullable: true
        - $ref: "#/components/parameters/apiVersion"
        - $ref: "#/components/parameters/authorization"
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ConfirmChallengeCommand'
      responses:
        '204':
          description: Desafio confirmado com sucesso.
      security:
        - Bearer: [ ]
components:
  schemas:
    CreateChallengeSimulatorCommand:
      required:
        - amount
        - card
        - merchant
      type: object
      properties:
        card:
          $ref: '#/components/schemas/ChallengeCard'
        deviceChannel:
          $ref: '#/components/schemas/DeviceChannel'
        merchant:
          $ref: '#/components/schemas/ChallengeMerchant'
        amount:
          $ref: '#/components/schemas/ChallengeAmount'
      additionalProperties: false
      
    ConfirmChallengeCommand:
      required:
        - documentNumber
      type: object
      properties:
        allowTransaction:
          type: boolean
        documentNumber:
          minLength: 1
          type: string
      additionalProperties: false
    
    ChallengeCard:
      required:
        - proxy
      type: object
      properties:
        proxy:
          minLength: 1
          type: string
      additionalProperties: false
    
    DeviceChannel:
      enum:
        - APP
        - BROWSER
      type: string
      description: Selecione o canal por meio do qual seu cliente receberá o desafio.
    
    ChallengeMerchant:
      required:
        - name
      type: object
      description: Nome do e-commerce no qual foi realizada a compra.
      properties:
        name:
          minLength: 1
          type: string
      additionalProperties: false
    
    ChallengeAmount:
      required:
        - currency
      type: object
      properties:
        value:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        currency:
          maxLength: 3
          minLength: 3
          type: string
      additionalProperties: false
    
    ChallengeSimulatorResponse:
      type: object
      properties:
        id:
          type: string
          description: Este valor corresponde ao challengeId que será utilizado na confirmação do desafio.
        
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
      bearerFormat: JWT
x-explorer-enabled: true
x-samples-enabled: true
x-samples-languages:
  - csharp
  - javascript
  - node
  - go
  - java
  - kotlin
  - php
  - python
  - ruby
  - swift
  - cplusplus
  - powershell
  - curl