env:
  COMPONENTS_LOCAL_URL: 'http://localhost:3320/commons/components#'
  SERVER_URL: 'https://raw.githubusercontent.com/acesso-bankly/open-api/'
  COMPONENTS_PATH: '/commons/components.yaml#'
  ORIGIN_BRANCH: ${{ github.head_ref }}
  TARGET_BRANCH: ${{ github.base_ref }}

name: ReadMe Pipeline
on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Valadating files
    steps:
    - uses: actions/checkout@v2
        
    - uses: jacobtomlinson/gha-find-replace@2.0.0
      name: Find and Replace Hostname
      if: ${{ success() && github.event_name != 'pull_request' }}
      with:
        find: ${{ env.COMPONENTS_LOCAL_URL }}
        replace: ${{ format('{0}{1}{2}', env.SERVER_URL, env.TARGET_BRANCH, env.COMPONENTS_PATH ) }}
        regex: false

    - uses: jacobtomlinson/gha-find-replace@2.0.0
      name: Find and Replace Hostname
      if: ${{ success() && github.event_name == 'pull_request' }}
      with:
        find: ${{ env.COMPONENTS_LOCAL_URL }}
        replace: ${{ format('{0}{1}{2}', env.SERVER_URL, env.ORIGIN_BRANCH, env.COMPONENTS_PATH ) }}
        regex: false

    - uses: mbowman100/swagger-validator-action@master
      name: Validate schemas
      with: 
        files: |
          ./apis/v1/accounts/schema.yaml
          ./apis/v1/boletos/schema.yaml
          ./apis/v1/cards/schema.yaml
          ./apis/v1/documents/schema.yaml
          ./apis/v1/events/schema.yaml
          ./apis/v1/helpers/schema.yaml
          ./apis/v1/holders/schema.yaml
          ./apis/v1/limits/schema.yaml
          ./apis/v1/oauth/schema.yaml
          ./apis/v1/paybill/schema.yaml
          ./apis/v1/pix/schema.yaml
          ./apis/v1/ted/schema.yaml
  
  deployDev:
    name: "Deploy / Dev"
    environment: development
    if: ${{ success() && (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') }}
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch      
          
      - uses: jacobtomlinson/gha-find-replace@2.0.0
        name: Find and Replace Hostname
        with:
          find: ${{ env.COMPONENTS_LOCAL_URL }}
          replace: ${{ format('{0}{1}{2}', env.SERVER_URL, steps.extract_branch.outputs.branch, env.COMPONENTS_PATH ) }}
          regex: false      
      
      - uses: readmeio/rdme@7.0.3
        name: Publish Holders API Reference to readme.io
        if: 
        with:
          rdme: openapi './apis/v1/holders/schema.yaml' --id=${{ secrets.HOLDERS_API_README_ID_KEY_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Accounts API Reference to readme.io
        with:
          rdme: openapi './apis/v1/accounts/schema.yaml' --id=${{ secrets.ACCOUNTS_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Auth API Reference to readme.io
        with:
          rdme: openapi './apis/v1/oauth/schema.yaml' --id=${{ secrets.AUTH_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Documents API Reference to readme.io
        with:
          rdme: openapi './apis/v1/documents/schema.yaml' --id=${{ secrets.KYC_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Events and Webhooks API Reference to readme.io
        with:
          rdme: openapi './apis/v1/events/schema.yaml' --id=${{ secrets.WEBHOOKS_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Pix API Reference to readme.io
        with:
          rdme: openapi './apis/v1/pix/schema.yaml' --id=${{ secrets.PIX_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish TED API Reference to readme.io
        with:
          rdme: openapi './apis/v1/ted/schema.yaml' --id=${{ secrets.TED_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
      
      - uses: readmeio/rdme@7.0.3
        name: Publish Limits API Reference to readme.io
        with: 
          rdme: openapi './apis/v1/limits/schema.yaml' --id=${{ secrets.LIMITS_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Cards API Reference to readme.io
        with: 
          rdme: openapi './apis/v1/cards/schema.yaml' --id=${{ secrets.CARDS_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Boletos API Reference to readme.io
        with:
          rdme: openapi './apis/v1/boletos/schema.yaml' --id=${{ secrets.BOLETO_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Helpers API Reference to readme.io
        with:
          rdme: openapi './apis/v1/helpers/schema.yaml' --id=${{ secrets.HELPER_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Pay Bill API Reference to readme.io
        with:
          rdme: openapi './apis/v1/paybill/schema.yaml' --id=${{ secrets.PAYBILL_API_README_OAS_ID_DEV }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

  deployProd:
    name: "Deploy / Prod"
    environment: production
    needs: [validate, deployDev]
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch      
          
      - uses: jacobtomlinson/gha-find-replace@2.0.0
        name: Find and Replace Hostname
        with:
          find: ${{ env.COMPONENTS_LOCAL_URL }}
          replace: ${{ format('{0}{1}{2}', env.SERVER_URL, steps.extract_branch.outputs.branch, env.COMPONENTS_PATH ) }}
          regex: false      
      
      - uses: readmeio/rdme@7.0.3
        name: Publish Holders API Reference to readme.io
        with:
          rdme: openapi './apis/v1/holders/schema.yaml' --id=${{ secrets.HOLDERS_API_README_ID_KEY }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Accounts API Reference to readme.io
        with:
          rdme: openapi './apis/v1/accounts/schema.yaml' --id=${{ secrets.ACCOUNTS_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Auth API Reference to readme.io
        with:
          rdme: openapi './apis/v1/oauth/schema.yaml' --id=${{ secrets.AUTH_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Documents API Reference to readme.io
        with:
          rdme: openapi './apis/v1/documents/schema.yaml' --id=${{ secrets.KYC_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Events and Webhooks API Reference to readme.io
        with:
          rdme: openapi './apis/v1/events/schema.yaml' --id=${{ secrets.WEBHOOKS_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish Pix API Reference to readme.io
        with:
          rdme: openapi './apis/v1/pix/schema.yaml' --id=${{ secrets.PIX_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
          
      - uses: readmeio/rdme@7.0.3
        name: Publish TED API Reference to readme.io
        with:
          rdme: openapi './apis/v1/ted/schema.yaml' --id=${{ secrets.TED_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
      
      - uses: readmeio/rdme@7.0.3
        name: Publish Limits API Reference to readme.io
        with: 
          rdme: openapi './apis/v1/limits/schema.yaml' --id=${{ secrets.LIMITS_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Cards API Reference to readme.io
        with: 
          rdme: openapi './apis/v1/cards/schema.yaml' --id=${{ secrets.CARDS_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Boletos API Reference to readme.io
        with:
          rdme: openapi './apis/v1/boletos/schema.yaml' --id=${{ secrets.BOLETO_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Helpers API Reference to readme.io
        with:
          rdme: openapi './apis/v1/helpers/schema.yaml' --id=${{ secrets.HELPER_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}

      - uses: readmeio/rdme@7.0.3
        name: Publish Pay Bill API Reference to readme.io
        with:
          rdme: openapi './apis/v1/paybill/schema.yaml' --id=${{ secrets.PAYBILL_API_README_OAS_ID }} --key=${{ secrets.APIS_README_OAS_KEY_DEV }}
